### ISSUE TITLE
Nepouzita premenna

### ISSUE THREAD

**Issue by MartinParak** [mhanis2/Oko_repo#1]
https://github.com/mhanis2/Oko_repo/blob/46edde7bee29a7aa2c6374d3ae84b9eae89724b9/src/util/CardUtil.java#L19
Tuto premennu mas zadefinovanu, ale nikde v metode sa nepouziva. Eclipse (kompilator) ta na to upozornuje warningom.

**Comment by mhanis2** [comment]
Odstranena
