### ISSUE TITLE
nepouzity import

### ISSUE THREAD

**Issue by MartinParak** [mhanis2/Oko_repo#2]
https://github.com/mhanis2/Oko_repo/blob/46edde7bee29a7aa2c6374d3ae84b9eae89724b9/src/util/CardUtil.java#L3
Zbytocny import. Eclipse (kompilator) ta na to upozornuje warningom. Keby si mal zapnuty source formatter, tak importy nemusis nikdy riesit.

Treba si zapnut source code formatter a nastavit save actions. Mali ste to v navode este na uplnom zaciatku kurzu, ze to mate pouzivat.

**Comment by mhanis2** [comment]
Odstraneny
