### ISSUE TITLE
Nevhodny nazov triedy

### ISSUE THREAD

**Issue by MartinParak** [mhanis2/Oko_repo#6]
https://github.com/mhanis2/Oko_repo/blob/46edde7bee29a7aa2c6374d3ae84b9eae89724b9/src/util/CardUtil2.java#L6

Naco potrebujes dve util triedy k rovnakej problematike? Z nazvu triedy ma byt jasne, co robi. Co znamena dvojka v nazve? Pouvazuj, ci sa nedaju spojit do jedinej triedy.

**Comment by mhanis2** [comment]
Tuto triedu som si nechal ako backup. Ale uz som ju odstranil.
