### ISSUE TITLE
nevhodny nazov

### ISSUE THREAD

**Issue by MartinParak** [mhanis2/Oko_repo#7]
https://github.com/mhanis2/Oko_repo/blob/46edde7bee29a7aa2c6374d3ae84b9eae89724b9/src/app/Start.java#L19
Vhodnejsi nazov by bol cardValidation. Nepouzivaj "of" v nazvoch, kde sa tomu da vyhnut, zbytocne sa predlzuje nazov premennej.

**Comment by mhanis2** [comment]
Nazov zmeneny na cardValidation.
