### ISSUE TITLE
Zbytocna cela struktura

### ISSUE THREAD

**Issue by MartinParak** [mhanis2/Oko_repo#8]
https://github.com/mhanis2/Oko_repo/blob/46edde7bee29a7aa2c6374d3ae84b9eae89724b9/src/factorycards/cards/Card.java#L6

Nedaju sa pridavat komentare k packages, takze to urobim tu, na vrchole hierarchie, v interface. Tyka sa to celej struktury package factorycards/cards.

- zbytocne si sa napisal, vsetko je to opakovany kod, nevyuzivas v nom vobec to, co ti objektovo-orientovany jazyk poskytuje- dedicnost a polymorfizmus. Ak by si si namiesto interface nechal triedu, v ktorej si mozes zadefinovat metody, tak ti ich staci zadefinovat v rodicovskej triede Card. A zistil by si, ze tie podtriedy vobec nebudes potrebovat. Na to ti staci vytvorit si objekt triedy Card s roznymi hodnotami atributov. Nemusis pre kazdu kartu vytvarat singleton.
Navyse instanciu karty si vytvaras ako konstantu (public), tak k nej vobec nepotrebujes pristupove metody getColor, getValue, getNameOfCard, ale mozes si atributy tahat rovno z nej...

Domaca uloha sa tykala factory - fungovat to funguje, ale je to naimplementovane nespravne. Ak chces robit singleton, instancia musi byt private. Ja som sa na webinari pomylil a uz som to ale aj niekolkokrat opravil. Instancia private, metoda na jej ziskanie public. Tu ju vsak vobec nepotrebujes. Mas triedu Card, jej objekty staci povytvarat pouzitim factory. Objekty, hracie karty, sa odlisuju len hodnotami atributov. Ty si si navyse este odpoznamkoval hodnotu karty, ktoru bude mat v bodoch, v enume Value.  Tu hodnotu budes potrebovat.

**Comment by mhanis2** [comment]
Struktura zmenena.
